import assert from 'node:assert/strict';
import { AislClient } from '../src/index.js';
const baseUrl = process.env.AISL_TEST_API_URL ?? 'http://127.0.0.1:18080';
const client = new AislClient(baseUrl);
const systems = await client.listSystems({ search: 'sdk-acceptance-rich' });
assert.ok(systems.some(s => s.system_id === 'sdk-acceptance-rich'));
const rev = await client.activeRevision('sdk-acceptance-rich');
assert.match(rev.revisionId, /^rev-/);
const products = await rev.listProducts();
assert.deepEqual(new Set(products.map(p => p.model_kind)), new Set(['code-declared-data-model', 'logical-storage-model-mapping', 'model-storage-semantics']));
const caps = new Set(await rev.getCapabilities());
assert.ok(caps.has('common.code-declared-data-model'));
assert.ok(caps.has('common.logical-storage-mapping'));
const found = await rev.searchDeclaredDataObjects({ search: 'Страна рождения', includeFields: true });
assert.equal(found.length, 1);
assert.equal(found[0].fqcn, 'com.acme.Individual');
const objectId = String(found[0].object_id);
const context = await rev.getDataModelObjectContext(objectId);
assert.equal(context.storage_context.status, 'available');
const rels = context.relationships;
const rel = rels.find(r => r.source_field === 'birthCountry');
assert.ok(rel);
const storage = rel.storage_semantics;
assert.equal(storage.status, 'ambiguous');
assert.equal(storage.candidate_mappings.length, 2);
const physical = rel.physical_mapping;
assert.equal(physical.physical_join_confirmed, false);
console.log(JSON.stringify({ status: 'PASS', system_id: rev.systemId, revision_id: rev.revisionId, product_count: products.length, capability_count: caps.size, storage_status: storage.status, candidate_mapping_count: storage.candidate_mappings.length, physical_join_confirmed: physical.physical_join_confirmed }, null, 2));
