from __future__ import annotations

CONFIGURATION_FACT_TYPES = (
    "configuration_entry",
    "configuration_object_observation",
    "configuration_reference_observation",
    "configuration_comment_observation",
)

SOURCE_OBSERVATION_FILES = (
    "call_argument_flow_observation.jsonl",
    "code_annotation.jsonl",
    "collection_mutation_observation.jsonl",
    "configuration_comment_observation.jsonl",
    "configuration_entry.jsonl",
    "configuration_object_observation.jsonl",
    "configuration_reference_observation.jsonl",
    "configuration_reference_resolution_observation.jsonl",
    "constructed_value_observation.jsonl",
    "cross_module_call_resolution_observation.jsonl",
    "cross_module_type_resolution_observation.jsonl",
    "module_boundary_interaction_observation.jsonl",
    "unresolved_module_reference_observation.jsonl",
    "external_dependency.jsonl",
    "build_dependency_observation.jsonl",
    "module_dependency_observation.jsonl",
    "gradle_project_observation.jsonl",
    "gradle_module_observation.jsonl",
    "gradle_external_dependency_observation.jsonl",
    "gradle_plugin_observation.jsonl",
    "gradle_version_catalog_observation.jsonl",
    "gradle_included_build_observation.jsonl",
    "gradle_source_set_observation.jsonl",
    "gradle_repository_observation.jsonl",
    "gradle_applied_script_observation.jsonl",
    "gradle_unresolved_dependency_observation.jsonl",
    "java_method_call_observation.jsonl",
    "java_call_parameter_binding_observation.jsonl",
    "java_call_result_binding_observation.jsonl",
    "java_method_parameter_observation.jsonl",
    "java_method_implementation_observation.jsonl",
    "java_method_parameter_correspondence_observation.jsonl",
    "java_method_reference_observation.jsonl",
    "tsa_annotation_observation.jsonl",
    "tsa_converter_configuration_observation.jsonl",
    "tsa_configuration_directive_observation.jsonl",
    "tsa_reference_operation_observation.jsonl",
    "tsa_key_expression_observation.jsonl",
    "tsa_storage_key_lineage_observation.jsonl",
    "tsa_reference_value_derivation_observation.jsonl",
    "storage_alias_assignment_observation.jsonl",
    "storage_record_observation.jsonl",
    "storage_reference_observation.jsonl",
    "type_reference_observation.jsonl",
)

REQUIRED_STATIC_DATA_MODEL_FILES = (
    "persistent_structures.json",
    "db_schema_tables.json",
    "db_schema_columns.json",
    "db_schema_keys.json",
    "db_schema_relationships.json",
    "db_schema_constraints.json",
    "db_schema_indexes.json",
    "db_schema_partitioning.json",
    "db_schema_sequences.json",
    "db_schema_triggers.json",
    "table_relationship_observations.json",
    "table_key_observations.json",
)

DETAIL_SECTIONS = (
    "physical_assets",
    "physical_asset_facts",
    "entities",
    "associations",
    "java_type_declarations",
    "attribute_derivations",
    "java_inheritance_observations",
    "effective_entity_fields",
    "effective_entity_associations",
    "physical_to_entity_mappings",
    "declared_value_sets",
    "data_dictionary",
    "evidence_gaps",
    "source_inspection_requests",
)

CORE_SECTIONS = ("domains", "entity_clusters", "generalizations")

# New evidence types may be introduced without invalidating fingerprints of older analyzer outputs
# that neither declare nor materialize them. Once present or declared, their bytes/counts are hashed.
FINGERPRINT_OPTIONAL_SOURCE_OBSERVATION_TYPES = frozenset({
    "configuration_reference_resolution_observation",
    "build_dependency_observation",
    "module_dependency_observation",
    "gradle_project_observation",
    "gradle_module_observation",
    "gradle_external_dependency_observation",
    "gradle_plugin_observation",
    "gradle_version_catalog_observation",
    "gradle_included_build_observation",
    "gradle_source_set_observation",
    "gradle_repository_observation",
    "gradle_applied_script_observation",
    "gradle_unresolved_dependency_observation",
    "storage_alias_assignment_observation",
    "storage_record_observation",
    "storage_reference_observation",
})
